import sys
from pathlib import Path
geodesic_dir = str(Path(__file__).parent.parent.resolve())
sys.path.append(geodesic_dir)

plotting_dir = str(Path(__file__).parent.parent.resolve() / "plotting")
sys.path.append(plotting_dir)

import geodesic_binning_plotting_main
import geodesic_binning_utilities_plotting as utils_plotting


#pickle_file_binning = "/Users/brucel/ecco/yip/ECCO-Insitu-Python/geodesic_binning/binning/binned_output/5_clustering_samples_per_profile/10242_geodesic_bins/num_subpolygons_max_2000/WOD_WO_2002_GLD__ncei_step_10_binning_data.pickle"
#pickle_file_plot = "/Users/brucel/ecco/yip/ECCO-Insitu-Python/geodesic_binning/binning/binned_output/5_clustering_samples_per_profile/10242_geodesic_bins/num_subpolygons_max_2000/WOD_WO_2002_GLD__ncei_step_10_plot_data.pickle"

#pickle_file_binning = "/Users/brucel/ecco/yip/ECCO-Insitu-Python/geodesic_binning/binning/binned_output/5_clustering_samples_per_profile/10242_geodesic_bins/num_subpolygons_max_2000/WOD_WO_1992_CTD_OSD__ncei_step_10_binning_data.pickle"
#pickle_file_plot = "/Users/brucel/ecco/yip/ECCO-Insitu-Python/geodesic_binning/binning/binned_output/5_clustering_samples_per_profile/10242_geodesic_bins/num_subpolygons_max_2000/WOD_WO_1992_CTD_OSD__ncei_step_10_plot_data.pickle"


pickle_file_binning = "/Users/brucel/ecco/yip/ECCO-Insitu-Python/geodesic_binning/binning/binned_output/5_clustering_samples_per_profile/10242_geodesic_bins/num_subpolygons_max_2000/WOD_WO_2021_GLD__ncei_step_10_binning_data.pickle"
pickle_file_plot = "/Users/brucel/ecco/yip/ECCO-Insitu-Python/geodesic_binning/binning/binned_output/5_clustering_samples_per_profile/10242_geodesic_bins/num_subpolygons_max_2000/WOD_WO_2021_GLD__ncei_step_10_plot_data.pickle"



geodesic_binning_plotting_main.plot_spawner(pickle_file_binning, pickle_file_plot)








"""
binning data output_file: /Users/brucel/ecco/yip/ECCO-Insitu-Python/geodesic_binning/binning/binned_output/50_clustering_samples_per_profile/10242_geodesic_bins/num_subpolygons_max_2000/ITP_WO_2004_CTD__ncei_step_10_binning_data.pickle
plot data output_file: /Users/brucel/ecco/yip/ECCO-Insitu-Python/geodesic_binning/binning/binned_output/50_clustering_samples_per_profile/10242_geodesic_bins/num_subpolygons_max_2000/ITP_WO_2004_CTD__ncei_step_10_plot_data.pickle
binning data output_file: /Users/brucel/ecco/yip/ECCO-Insitu-Python/geodesic_binning/binning/binned_output/50_clustering_samples_per_profile/10242_geodesic_bins/num_subpolygons_max_2000/WOD_WO_1992_CTD_OSD__ncei_step_10_binning_data.pickle
plot data output_file: /Users/brucel/ecco/yip/ECCO-Insitu-Python/geodesic_binning/binning/binned_output/50_clustering_samples_per_profile/10242_geodesic_bins/num_subpolygons_max_2000/WOD_WO_1992_CTD_OSD__ncei_step_10_plot_data.pickle
binning data output_file: /Users/brucel/ecco/yip/ECCO-Insitu-Python/geodesic_binning/binning/binned_output/50_clustering_samples_per_profile/10242_geodesic_bins/num_subpolygons_max_2000/WOD_WO_2002_GLD__ncei_step_10_binning_data.pickle
plot data output_file: /Users/brucel/ecco/yip/ECCO-Insitu-Python/geodesic_binning/binning/binned_output/50_clustering_samples_per_profile/10242_geodesic_bins/num_subpolygons_max_2000/WOD_WO_2002_GLD__ncei_step_10_plot_data.pickle
binning data output_file: /Users/brucel/ecco/yip/ECCO-Insitu-Python/geodesic_binning/binning/binned_output/50_clustering_samples_per_profile/10242_geodesic_bins/num_subpolygons_max_2000/ARGO_WO_2001_PFL_A__ncei_step_10_binning_data.pickle
plot data output_file: /Users/brucel/ecco/yip/ECCO-Insitu-Python/geodesic_binning/binning/binned_output/50_clustering_samples_per_profile/10242_geodesic_bins/num_subpolygons_max_2000/ARGO_WO_2001_PFL_A__ncei_step_10_plot_data.pickle
binning data output_file: /Users/brucel/ecco/yip/ECCO-Insitu-Python/geodesic_binning/binning/binned_output/50_clustering_samples_per_profile/10242_geodesic_bins/num_subpolygons_max_2000/ARGO_WO_2015_PFL_A__ncei_step_10_binning_data.pickle
plot data output_file: /Users/brucel/ecco/yip/ECCO-Insitu-Python/geodesic_binning/binning/binned_output/50_clustering_samples_per_profile/10242_geodesic_bins/num_subpolygons_max_2000/ARGO_WO_2015_PFL_A__ncei_step_10_plot_data.pickle
"""
